#!/usr/bin/env Rscript

# Package directories
dirname <- "oposSOM"
datadir <- file.path(dirname, "data")

# Remove existing package dir
if (file.exists(dirname)) {
  cat("* remove existing package dir:", dirname, "\n")
  unlink(dirname, recursive=T)
}
dir.create("oposSOM")

# Copy everything we need
for (f in c("R", "DESCRIPTION", "NAMESPACE")) {
  cat("* copy", f, "\n")
  file.copy(file.path("src", f), file.path(dirname), recursive=T)
}

# Move data into the package
cat("* create data dir:", datadir, "\n")
dir.create(datadir)

filename <- file.path("src", "data", "geneset_collection.csv")
cat("* load", filename, "\n")
genesets <- read.csv2(filename, as.is=T)

# collapse gene sets in more than one cell
for(i in 1:nrow(genesets)) {
  cells <- sum(sapply(genesets[i, c(4:ncol(genesets))], nchar) > 0)

  if (cells > 1) {
    genesets[i,4] = paste(genesets[i, c(4:(4+cells-1))], collapse=",")
  }
}

opossom.genesets <- apply(genesets, 1, function(x) {
  list(Genes=as.vector(x["Genes"]), Type=as.vector(x["Type"]))
})

names(opossom.genesets) <- genesets[,"Name"]

opossom.genesets <- lapply(opossom.genesets, function(x) {
  x$Genes = strsplit(x$Genes, ",")[[1]]
  return(x)
})

filename <- file.path(datadir, "opossom.genesets.RData")
cat("* save", filename, "\n")
save(opossom.genesets, file=filename, compress="xz")

# Build and Check
cat("\n>> R CMD build", dirname, "\n")
system(paste("R CMD build", dirname))

cat(">> R CMD check", dirname, "\n")
system(paste("R CMD check", dirname))

# Install
install.packages("oposSOM_0.3.0.tar.gz")
